
import java.util.Iterator;
import java.util.Vector;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author estudiantelis
 */
public class IngresaPropiedades extends javax.swing.JFrame {

    /**
     * Creates new form IngresaPropiedades
     */
    private Vector index;
    private boolean flag = false;
    private String nombre;
    private Vector simbolos;
    private Vector estados;
    private int m;
    private int n;
    
    public IngresaPropiedades() {
        initComponents();
        cambiaEstado(false);
        chkStatusInitial.setSelected(true);
        rbReject.setSelected(true);
        n=0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnCreateAuto = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtSymbol = new javax.swing.JTextField();
        btnAddSymbol = new javax.swing.JButton();
        txtViewSymbol = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtStatusAuto = new javax.swing.JTextField();
        chkStatusInitial = new javax.swing.JCheckBox();
        btnAddStatus = new javax.swing.JButton();
        rbAceptation = new javax.swing.JRadioButton();
        rbReject = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtViewStatus = new javax.swing.JTextArea();
        btnFinish = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ingresar Propiedades del Automata");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Nombre del Automata:");

        btnCreateAuto.setText("Crear Automata");
        btnCreateAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAutoActionPerformed(evt);
            }
        });

        jLabel2.setText("Simbolo de Entrada");

        txtSymbol.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSymbolKeyTyped(evt);
            }
        });

        btnAddSymbol.setText("Agregar");
        btnAddSymbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSymbolActionPerformed(evt);
            }
        });

        txtViewSymbol.setText("λ");

        jLabel3.setText("Estados del Automata");

        chkStatusInitial.setText("Estado Inicial");

        btnAddStatus.setText("Agregar");
        btnAddStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStatusActionPerformed(evt);
            }
        });

        rbAceptation.setText("Aceptacion");

        rbReject.setText("Rechazo");
        rbReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbRejectActionPerformed(evt);
            }
        });

        txtViewStatus.setColumns(20);
        txtViewStatus.setRows(5);
        jScrollPane1.setViewportView(txtViewStatus);

        btnFinish.setText("Terminar");
        btnFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinishActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(txtViewSymbol, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtStatusAuto))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSymbol, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbAceptation)
                                .addGap(18, 18, 18)
                                .addComponent(rbReject)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(chkStatusInitial)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAddSymbol)
                                    .addComponent(btnCreateAuto)
                                    .addComponent(btnAddStatus))))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFinish)
                .addGap(269, 269, 269))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreateAuto))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSymbol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddSymbol))
                .addGap(18, 18, 18)
                .addComponent(txtViewSymbol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtStatusAuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkStatusInitial)
                    .addComponent(btnAddStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbAceptation)
                    .addComponent(rbReject))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFinish)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAutoActionPerformed
        // TODO add your handling code here:
        nombre = txtName.getText();
        if(nombre.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Por favor ingrese un nombre para el automata", "Alerta!!", 2);
            txtName.requestFocus();
            return;
        }
        simbolos = new Vector();
        estados = new Vector();
        cambiaEstado(true);
        btnCreateAuto.setEnabled(false);
        txtName.setEditable(false);
        txtSymbol.requestFocus();
        chkStatusInitial.setEnabled(true);
        txtName.setEnabled(false);
    }//GEN-LAST:event_btnCreateAutoActionPerformed

    private void btnAddSymbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSymbolActionPerformed
        // TODO add your handling code here:
        if(!txtSymbol.getText().equals("")) {
            if(!existe1(txtSymbol.getText(), simbolos)) {
                n++;
                simbolos.add(txtSymbol.getText());
                txtViewSymbol.setText(txtViewSymbol.getText() + ", " + txtSymbol.getText());
                txtSymbol.setText("");
                txtSymbol.requestFocus();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Ya Ingreso este simbolo", "ERROR !!!", 0);
                txtSymbol.setText("");
                txtSymbol.requestFocus();
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Debe ingresar un caracter que represente el simbolo de entrada!", "ALERTA !!!", 2);
            txtSymbol.requestFocus();
        }
    }//GEN-LAST:event_btnAddSymbolActionPerformed

    private void btnAddStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStatusActionPerformed
        // TODO add your handling code here:
        if(!txtStatusAuto.getText().equals("")) {
            m++;
            String est = "E" + m;
            boolean h = false;
            boolean f = false;
            
            if(chkStatusInitial.isSelected()) {
                h = true;
            }
            if(rbAceptation.isSelected()) {
                f = true;
            }
            Estado a = new Estado(est, txtStatusAuto.getText(), h, f);
            estados.add(a);
            
            if(h) {
                flag = true;
                if(f) {
                    txtViewStatus.setText(txtViewStatus.getText() + "\n" + "*" + est + " : " + txtStatusAuto.getText() + "(Aceptacion)");
                } else {
                    txtViewStatus.setText(txtViewStatus.getText() + "\n" + "*" + est + " : " + txtStatusAuto.getText());
                }
                chkStatusInitial.setEnabled(false);
            } else {
                if(f) {
                    txtViewStatus.setText(txtViewStatus.getText() + "\n" + est + " : " + txtStatusAuto.getText() + "(Aceptacion)");
                } else {
                    txtViewStatus.setText(txtViewStatus.getText() + "\n" + est + " : " + txtStatusAuto.getText());
                }
            }
            
            chkStatusInitial.setSelected(false);
            txtStatusAuto.selectAll();
            txtStatusAuto.requestFocus();
            h = false;
            f = false;
        } else {
            JOptionPane.showMessageDialog(rootPane, "Debe ingresar un nombre para el estado", "Alerta!!!", 2);
            txtStatusAuto.requestFocus();
        }
    }//GEN-LAST:event_btnAddStatusActionPerformed

    private void btnFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinishActionPerformed
        // TODO add your handling code here:
        if(flag == true) {
            Vector a[][] = new Vector[m + 1][n + 2];
            for (int gg = 0; gg < m + 1; gg++) {
                for (int hh = 0; hh < n + 2; hh++) {
                    a[gg][hh] = new Vector();
                }
            }

            for (int i = 0; i < n; i++) {
                try {
                    a[0][i + 1].add(simbolos.get(i).toString());
                } catch (Exception p) {
                    a[0][i + 1] = new Vector();
                    a[0][i + 1].add(simbolos.get(i).toString());
                }
            }

            for (int i = 0; i < m; i++) {
                Estado e = (Estado) estados.get(i);
                try {
                    a[i + 1][0].add(e.getIcono());
                } catch (Exception p) {
                    a[i + 1][0] = new Vector();
                    a[i + 1][0].add(e.getIcono());
                }
            }
            a[0][n + 1] = new Vector();
            a[0][n + 1].add("λ");

            simbolos.add("λ");

            Automata aut = new Automata(nombre, simbolos, estados, a);
            IngresaAutomata ing = new IngresaAutomata(aut, index);
            ing.setVisible(true);
            this.setVisible(false);
            flag = false;
        }
    }//GEN-LAST:event_btnFinishActionPerformed

    private void txtSymbolKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSymbolKeyTyped
        // TODO add your handling code here:
        if (txtSymbol.getText().length() == 1) {
            evt.consume();
        }
    }//GEN-LAST:event_txtSymbolKeyTyped

    private void rbRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRejectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbRejectActionPerformed
    private void cambiaEstado(boolean a) {
        txtSymbol.setEditable(a);
        btnAddSymbol.setEnabled(a);
        txtStatusAuto.setEditable(a);
        btnAddStatus.setEnabled(a);
        btnFinish.setEnabled(a);
        chkStatusInitial.setEnabled(a);
    }
    private boolean existe1(String a, Vector s) {
        Iterator io = s.iterator();
        while(io.hasNext()) {
            String j = (String)io.next();
            if(j.equals(a)) {
                return true;
            }
        }
        return false;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresaPropiedades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresaPropiedades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresaPropiedades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresaPropiedades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresaPropiedades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddStatus;
    private javax.swing.JButton btnAddSymbol;
    private javax.swing.JButton btnCreateAuto;
    private javax.swing.JButton btnFinish;
    private javax.swing.JCheckBox chkStatusInitial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbAceptation;
    private javax.swing.JRadioButton rbReject;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtStatusAuto;
    private javax.swing.JTextField txtSymbol;
    private javax.swing.JTextArea txtViewStatus;
    private javax.swing.JTextField txtViewSymbol;
    // End of variables declaration//GEN-END:variables

    
}
